owner: "qiagu"
remote_repository_url: "https://github.com/ohsu-comp-bio/cellpose_segmentation/tree/master"
homepage_url: "https://github.com/MouseLand/cellpose"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  cellpose_segmentation:
    description: "Generate cell segmentation masks for microscopy images using Cellpose"
    include:
      - cp_segmentation.py
      - cp_segmentation.xml
